runtime: python311
service: default

env_variables:
  PYTHON_VERSION: "3.11"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

entrypoint: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
