# Cloud Build configuration for Streamlit UI deployment to App Engine
# This file automatically deploys the UI when code is pushed to GitHub

steps:
  # Step 1: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "app.yaml", "--quiet", "--version", "$COMMIT_SHA"]

# No images to store for App Engine
# Build timeout
timeout: "600s"

# Machine type for faster builds
options:
  machineType: "E2_HIGHCPU_8"
