services:
  # Stock Prediction API Service
  - type: web
    name: stock-prediction-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy pandas scikit-learn tensorflow xgboost lightgbm
      pip install fastapi uvicorn gunicorn pydantic
      pip install requests pyyaml plotly mlflow
    startCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # - key: MLFLOW_TRACKING_URI
      #   value: https://stock-prediction-mlflow.onrender.com
      - key: API_HOST
        value: 0.0.0.0
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: API_KEY_ENABLED
        value: false
    healthCheckPath: /health
    autoDeploy: true
    branch: main

  # Stock Prediction UI Service
  - type: web
    name: stock-prediction-ui
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install streamlit plotly pandas numpy requests pyyaml
    startCommand: streamlit run src/frontend/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_URL
        value: https://stock-prediction-api.onrender.com
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
    healthCheckPath: /_stcore/health
    autoDeploy: true
    branch: main

  # MLflow Tracking Service (Commented out - Memory issues on free tier)
  # - type: web
  #   name: stock-prediction-mlflow
  #   env: python
  #   plan: free
  #   buildCommand: |
  #     pip install --upgrade pip
  #     pip install mlflow==2.8.0
  #   startCommand: mlflow server --host 0.0.0.0 --port $PORT --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlartifacts --workers 1 --max-artifact-root-size 100MB
  #   envVars:
  #     - key: PYTHON_VERSION
  #       value: 3.11.0
  #     - key: MLFLOW_TRACKING_URI
  #       value: https://stock-prediction-mlflow.onrender.com
  #   healthCheckPath: /health
  #   autoDeploy: true
  #   branch: main
